name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CODEOWNERS Check
        uses: ./.github/actions/check-codeowners
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
